### ISSUE TITLE
Hidden Forbidden Holy Ground Bug

### ISSUE THREAD

**Issue by Tellilum** [Tellilum/.hack-fragment-Definitive-Translation#10]
Δ Hidden Forbidden Holy Ground has a nasty bug where the game will softlock/crash upon attempting to enter the field.

**Comment by Tellilum** [comment]
Adding Redundant label due to the bug not being caused by TelliPatch

**Comment by vec702** [comment]
![Hidden Forbidden Holy Ground Bug](https://user-images.githubusercontent.com/9296352/96004060-ed60bf80-0e08-11eb-95d3-035c1cad0b88.PNG) here's the two lines that specifically cause this bug.
