### ISSUE TITLE
Game crash in Offline Forest areas

### ISSUE THREAD

**Issue by rlstine** [Tellilum/.hack-fragment-Definitive-Translation#11]
Game crashes when I open chests in Forest fields. The chest opens, the the game crashes right before a message saying that's in the chest would normally appear. Only seems to happen in offline mode, and only on maps where you start in a dungeon rather than in a field. It's also worth noting that it seems to only affect physical PS2 consoles.

**Comment by rlstine** [comment]
Encountered another crash (unsure if related to the above) in offline storymode. When I attempt to go to Theta Echoing Remains Requiem in the Chaos Gate Words List the game will crash immediately. I can enter the words individually into the New Keyword option and that seems to be a workaround.

**Comment by Finzenku** [comment]
> 
> 
> Encountered another crash (unsure if related to the above) in offline storymode. When I attempt to go to Theta Echoing Remains Requiem in the Chaos Gate Words List the game will crash immediately. I can enter the words individually into the New Keyword option and that seems to be a workaround.

This was a separate issue caused by there being two keywords with the same name "Remains". This and other duplicate keywords are being changed in the next release.

**Comment by Tellilum** [comment]
Issue has been resolved. Closing.
