### ISSUE TITLE
Provide a buildbot/pipeline to build the translated files

### ISSUE THREAD

**Issue by Risae** [Tellilum/.hack-fragment-Definitive-Translation#12]
It would be great to be able to compile all the files yourself, such as with a build script. Currently only xDelta files are provided.

**Comment by vec702** [comment]
We've created a tool to translate your game [here](https://github.com/robby-u/tellipatch/releases).

This repo only includes part of a collaborative effort to translate .hack//fragment. The link above is the "final" product.

Thanks! =)
\- vector
