### ISSUE TITLE
Potential softlock

### ISSUE THREAD

**Issue by Sonikku2008** [Tellilum/.hack-fragment-Definitive-Translation#6]
Version: 1.1

VectorNyao patch: Idk what this is, so unless it was bundled in your translation patch, no.

Class: Twin Blade

Level: 26

Armor: Fire Lion Hood/Magus Robes/Divine Gloves/Oaken Solleret

Weapon: Suigetsu

Steps to reproduce bug (if any): I've no clue how the bug happened. I encountered a room full of Mimic-type enemies (untranslated) in Rachel and Subaru's story dungeon on Sigma server (area level is 54), and I attempted to cast Mumyn Lei on them. A couple attempts later, I find myself unable to do jack shit except rotate the camera, the mimics are rooted in place for some reason, and the only damage we're taking is whenever Rachel and Subaru attack each other while confused. Subaru eventually kills Rachel, and the softlock began there. Due to the enemy's physical tolerance and Subaru's lack of magic skills (I had issued Use Magic Skills before I became immobile), as well as Subaru's proximity to the enemy and the mimics only being capable of casting confuse because my being locked in place somehow also locked THEM in place, the game became softlocked. The only way I got out of this was by utilizing Cheat Engine to give Subaru the Charm status effect, forcing her to kill me, which freed the Mimics. So whatever bug happened directly had an effect on the enemies as well as my character.

I do not know if this is an issue with the translation patch. I had switched to this patch today, but did not previously have problems using Mumyn Lei against other enemies. These enemies could be the problem rather than my skill specifically. I had been using a new weapon, Suigetsu, for a period of time as well (a couple combats in the Hongik server, I was able to land Mumyn Lei on an enemy and did not have any issues there). Just throwing out there as many possibilities as possible.

Online/Offline?: Happened in offline. Could happen online in theory, but at least in online you can Escape out so it's not a true softlock.

Images of the bug (if any): https://cdn.discordapp.com/attachments/235056521975693312/761429814972252170/unknown.png The state of combat as it was before I started using cheat engine to see if I could set my HP to 0 and game over that way. (It doesn't work.) Notably, you can see the enemy info window there, suggesting my casting animation never ended from the game's point of view, as I'm not close enough to any enemies to melee target them.

Edit to add new template items.

**Comment by Sonikku2008** [comment]
So I know you said not to use the skill, but the best way to narrow down the precise cause is to test. And I do have a save state in a safe zone in case shit happens.

I can rule out the mimic enemies as the specific cause, as it happened in an area where they don't show up.

I had my movement frozen upon running into close proximity of my allies, suggesting I had walked into the AoE range of a spell that did not complete casting. This locked all of my characters in place -- until Subaru died anyway, but that only freed her -- so the Charm trick I used previously is insufficient to escape this one.

The enemies I fought did have the means to disable my actions -- this time through paralyze -- and my actions became completely sealed again at some point during this.

As a result of this testing, I believe Mumyn Lei itself is not the problem; it is any action that prevents you from taking any direct action (paralyze, confuse, charm, sleep) causing casting animations to not end from the game's purview. I do not currently understand why this did not happen in online, as I had repeatedly cast it during rare item dungeon runs without issue, but I suppose it is possible the enemies died too quickly to note its effects.

Since this issue does not come up in Coldbird's old build, I think I will revert back to that translation for the time being. I hope this new information is able to help you narrow down the cause of this bug. I've attached a new image of my current location at the time I encountered this problem again, this area is the second to last story dungeon in Lambda server offline.
![image](https://user-images.githubusercontent.com/72248727/94980143-027a4c00-04f5-11eb-8f5f-d96495643b52.png)

**Comment by Sonikku2008** [comment]
One more thing to add I forgot about. The mage in the background is casting something. I don't know what, but it is not having any effect that I can see, and there's no "miss" prompt suggesting he's missing. I know it has magic attacks, but it seems to be unable to use them.

**Comment by Tellilum** [comment]
> One more thing to add I forgot about. The mage in the background is casting something. I don't know what, but it is not having any effect that I can see, and there's no "miss" prompt suggesting he's missing. I know it has magic attacks, but it seems to be unable to use them.

Thank you for adding more information! I'll run two tests, run with an untranslated ISO and one with my translation, just to see if it's a bug itself or something to do with my translation.

**Comment by Sonikku2008** [comment]
Updated report to include new template information.
